### PR TITLE
Various changes (see description)

### PR DESCRIPTION
**Pull request by alairock**
I don't expect this to be merged in, as it was more for making using this script easier for my own purposes, but maybe you might think it was interesting and could help other users use the script without having to worry so much about finding serial/midi ports. 

- Using PyInquirer to get a list of available Serial com ports and interactively select it
- Open virtual In/Out midi ports if port passed cannot be found
- Added poetry/pyproject.toml for virtual environment management
- PEP 8 autoformatting

### CODE REVIEW

**Comment by raspy135** [comment]
Thanks, I will check the change when I have time.

**Comment by raspy135** [comment]
Hi,
I checked the change. 
How can I utilize the virtual MIDI port? I don't see the ports from my DAW.(I tested on OS X)

**Comment by alairock** [comment]
Sorry for the delayed response. @raspy135 The virtual port should just be created if you don't pass the midi in/out ports. 

`print('Opening Virtial out port: ', vport_name)`

So if you don't see this print in the terminal, then it didn't create the virtual port. It shows up in logic and garage band when I run it.

**Comment by rezotsik** [comment]
Hello i'm new on github i made midi keyboard with arduino mega hairless midi doesn't work on my laptop anymore because of new mac os isn't compatible with 32 bit apps. I tried to this method but i'm geting problem `Serial port opening error.
INFO:root:IN : 'IAC Bus 1 Bus 1','USB2.0-MIDI Port 1'
INFO:root:OUT : 'IAC Bus 1 Bus 1','USB2.0-MIDI Port 1','USB2.0-MIDI Port 2'
INFO:root:Hit ctrl-c to exit
MIDI OUT Device name is incorrect. Please use listed device name.`
could you help me ?

**Comment by raspy135** [comment]
Did you use this branch? What command line did you pass?

**Pull request merged**
